# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:      pretty
baseurl: 	    	/2018fUVA-CS4501MachineLearning/
url:            https://qiyanjun.github.io/

# Setup
title:            	"2018 Fall CS4501 - Machine Learning"
tagline:          	"2018 Fall"
description:        "TuTh 3:30PM - 4:45PM @ Rice 130"
future: 			true

author:
  name:           'Yanjun Qi'
  url:            https://twitter.com/Qdatalab
